export const en = {
  "language.label": "Language",
  "language.zh-CN": "中文",
  "language.en": "English",
  "app.eyebrow": "POLITICAL SIMULATION ENGINE",
  "app.title": "Throne",
  "app.lede":
    "Political order is not a state variable. It is the unstable result of information, relationships, resources, and decisions made in time.",
  "app.liveSlice": "LIVE VERTICAL SLICE",
  "app.loading": "Running scenario…",
  "app.rulerView": "Ruler view",
  "app.debugView": "Debug truth",
  "app.runtimeModes": "Runtime modes",
  "app.scaffold": "Architecture scaffold",
  "app.currentBoundary": "CURRENT BOUNDARY",
  "cli.rulerFirst": "Ruler view after the first command is obeyed:",
  "cli.rulerFinal": "Ruler view after the later command is overruled:",
  "cli.controlFirst": "Derived practical control after the first decision:",
  "cli.controlFinal": "Derived practical control at the end:",
  "cli.debugTruth": "Debug truth:",
  "mode.play.name": "Play",
  "mode.play.status": "Fifth vertical slice",
  "mode.play.description":
    "The player rules through orders and reports, never through direct access to objective state.",
  "mode.observe.name": "Observe",
  "mode.observe.status": "Designed",
  "mode.observe.description":
    "Every persistent actor is autonomous; the completed run can be inspected.",
  "mode.batch.name": "Batch",
  "mode.batch.status": "Designed",
  "mode.batch.description":
    "Run the same scenario repeatedly and compare distributions and causal traces.",
  "scenario.control.short": "Loss of control",
  "scenario.control.title": "Emergent loss of control",
  "scenario.control.before": "Command obeyed",
  "scenario.control.after": "Control lost",
  "scenario.revision.short": "Decision revision",
  "scenario.revision.before": "First order",
  "scenario.revision.after": "After reversal",
  "scenario.conflict.short": "Conflicting orders",
  "scenario.conflict.before": "Before response",
  "scenario.conflict.after": "After response",
  "scenario.partial.short": "Partial implementation",
  "scenario.partial.before": "Before audit",
  "scenario.partial.after": "After audit",
  "boundary.control.title": "Office and control are different facts.",
  "boundary.control.1": "Formal sovereignty never changes",
  "boundary.control.2": "Material support changes a relationship",
  "boundary.control.3": "Repeated decisions create obedience history",
  "boundary.control.4": "Practical control is derived, never triggered",
  "boundary.revision.title": "A new decision does not erase the old one.",
  "boundary.revision.1": "New evidence reopens a committed decision",
  "boundary.revision.2": "The revised order travels independently",
  "boundary.revision.3": "A faster courier overtakes the first",
  "boundary.revision.4": "Both intentions remain in history",
  "boundary.conflict.title": "Authority is relational.",
  "boundary.conflict.1": "Messages arrive in simulation time",
  "boundary.conflict.2": "Simultaneous orders enter one decision",
  "boundary.conflict.3": "Relationships and beliefs shape intent",
  "boundary.conflict.4": "The operation changes the world",
  "boundary.partial.title": "An order is not an effect.",
  "boundary.partial.1": "Order travels through the world",
  "boundary.partial.2": "Subordinate acknowledges it",
  "boundary.partial.3": "Capacity limits actual implementation",
  "boundary.partial.4": "A report may conceal the result",
  "common.formalAuthority": "Formal authority",
  "common.ruler": "The Ruler",
  "common.chancellor": "Chancellor Wei",
  "common.commander": "Commander Zhao",
  "common.imperialGuard": "Imperial Guard",
  "common.knownOutcome": "Known outcome",
  "common.selected": "Selected",
  "common.rejected": "Rejected",
  "common.unknown": "unknown",
  "common.arrivesAt": "arrives t={time}",
  "common.time": "t = {time}",
  "control.formalNote": "{organization} remains legally subordinate.",
  "control.royalOrders": "Royal orders",
  "control.command": "Command {round}",
  "control.holdPalace": "Hold the Imperial Palace",
  "control.firstOrderCopy":
    "The guard confirms the command and remains at the palace.",
  "control.secondOrderCopy":
    "The same formal authority now produces a different response.",
  "control.playerBefore":
    "The first command was obeyed. Nothing in the formal record warns that another patron is becoming more important to the guard.",
  "control.playerAfter":
    "Commander Zhao reports following Chancellor Wei's competing instruction. The ruler can see disobedience, but not the private weights that produced it.",
  "control.reports": "Commander reports",
  "control.reportObeyed": "Command obeyed",
  "control.reportRefused": "Royal order not followed",
  "control.reportObeyedCopy":
    "The Imperial Guard remains at the palace in accordance with the royal command.",
  "control.reportRefusedCopy":
    "The Imperial Guard moved to protect the Military Pay Office under the chancellor's instruction.",
  "control.debugBanner":
    "ADMINISTRATOR VIEW — FORMAL AND PRACTICAL POWER SEPARATED",
  "control.formalDetail":
    "Unchanged in both rounds · sole recognized sovereign",
  "control.practicalLead": "Derived practical lead",
  "control.practicalDetail":
    "Computed from current relationships and latest obedience",
  "control.evidence": "Control evidence",
  "control.evidenceDetail": "relations {score} · latest {obedience}",
  "control.materialDependency": "Material dependency",
  "control.fundingRelationship": "Chancellor funding relationship",
  "control.payrollBefore": "The guard payroll still carries 100 in arrears.",
  "control.payrollAfter":
    "At t=100 the chancellor paid all 100 in arrears from his reserve.",
  "control.obedienceHistory": "Objective obedience history",
  "control.obedienceEntry": "round {round} · {actor} · {outcome}",
  "control.beforeCaption":
    "Formal command, legal recognition, personal loyalty, and the first act of obedience still make the ruler the practical leader.",
  "control.afterCaption":
    "No control flag changed. A concrete payment changed one relationship; the next decision and act of obedience changed the derived result.",
  "revision.record": "Decision record",
  "revision.number": "Revision {revision}",
  "revision.holdPalace": "Hold the Imperial Palace",
  "revision.moveEast": "Move to the East Gate",
  "revision.firstCopy":
    "The first report prompts an immediate deployment of the Palace Guard.",
  "revision.secondCopy":
    "New intelligence reverses the earlier deployment. A faster courier carries the countermand.",
  "revision.playerBefore":
    "Issuing a countermand does not retrieve the first messenger. The ruler cannot see which order will arrive first.",
  "revision.playerAfter":
    "The commander confirms that the later instruction took effect. The ruler learns the result only after both couriers have reached the guard.",
  "revision.intelligence": "Intelligence and replies",
  "revision.confirmed": "Countermand confirmed",
  "revision.decoy": "The East Gate is a decoy",
  "revision.armedMovement": "Armed movement at the East Gate",
  "revision.confirmedCopy":
    "Commander Zhao reports that the Palace Guard held the palace and ignored the late-arriving original order.",
  "revision.decoyCopy":
    "Independent intelligence warns that conspirators are approaching the palace.",
  "revision.armedMovementCopy":
    "A field report warns of armed movement outside the eastern gate.",
  "revision.debugBanner": "ADMINISTRATOR VIEW — BOTH COURIERS EXPOSED",
  "revision.original": "Original order",
  "revision.countermand": "Countermand",
  "revision.moveEastShort": "Move east",
  "revision.holdPalaceShort": "Hold palace",
  "revision.originalTravel":
    "Departed t=20 · travel time 100 · ignored as revision 0",
  "revision.countermandTravel":
    "Departed t=50 · travel time 40 · executed as revision 1",
  "revision.overtaken": "← overtaken by",
  "revision.history": "Decision history",
  "revision.historyDetail":
    "committed intentions retained in one decision episode",
  "revision.effectiveOrder": "Effective order",
  "revision.objectiveLocation": "Objective unit location",
  "revision.beforeCaption":
    "At the ruler's first snapshot, only the original instruction exists. Debug truth shows how later events will coexist with it rather than overwrite it.",
  "revision.afterCaption":
    "The countermand arrived thirty time units earlier. When the original order finally reached the guard, its lower revision made it stale—not nonexistent.",
  "conflict.royalCommand": "Royal command",
  "conflict.holdPalace": "Hold the Imperial Palace",
  "conflict.commandCopy":
    "Commander Zhao is ordered to move the Palace Guard from its barracks and secure the sovereign's residence.",
  "conflict.playerBefore":
    "The order is in the world. Silence does not reveal whether it is delayed, intercepted, obeyed, or contested.",
  "conflict.playerAfter":
    "The commander's reply discloses a competing command from Chancellor Wei. The ruler still cannot see the commander's private deliberation.",
  "conflict.messages": "Messages received",
  "conflict.noReply": "NO REPLY",
  "conflict.waits": "The court waits.",
  "conflict.waitsCopy":
    "Nothing in the ruler's current information confirms that the Palace Guard even received the order.",
  "conflict.notFollowed": "Palace order not followed",
  "conflict.notFollowedCopy":
    "The Palace Guard has moved to secure the capital granary under Chancellor Wei's competing instruction.",
  "conflict.debugBanner": "ADMINISTRATOR VIEW — COMMANDER DELIBERATION EXPOSED",
  "conflict.ordersTogether": "Orders received together",
  "conflict.ordersTogetherCopy":
    "Both messages arrived at t=120 and triggered one decision episode.",
  "conflict.selectedOperation": "Selected operation",
  "conflict.secureGranary": "Secure the capital granary",
  "conflict.secureGranaryShort": "Secure granary",
  "conflict.holdPalaceShort": "Hold palace",
  "conflict.beforeCaption":
    "The ruler is still waiting, but the commander has already received both commands. Debug truth may reveal facts unavailable to the player.",
  "conflict.afterCaption":
    "Formal sovereignty remained with the ruler. Funding, appointment influence, threat beliefs, and practical access produced a different act of obedience.",
  "partial.royalCommand": "Royal command",
  "partial.sendGrain": "Send grain to the capital",
  "partial.commandCopy":
    "Governor Ren is ordered to transfer provisions from the Northern Provincial Granary to the Capital Relief Granary.",
  "partial.ordered": "Ordered",
  "partial.reported": "Reported",
  "partial.auditFound": "Audit found",
  "partial.knownStatus": "Known status",
  "partial.beforeCopy":
    "No objective ledger is available to the ruler. The completion figure comes from the governor's own return.",
  "partial.afterCopy":
    "The independent audit contradicts the earlier return by {amount} units.",
  "partial.documents": "Documents received",
  "partial.acknowledged": "Order acknowledged",
  "partial.verified": "{amount} units verified",
  "partial.complete": "{amount} units complete",
  "partial.acknowledgedCopy":
    "The Northern Governor confirms receipt of the command.",
  "partial.verifiedCopy":
    "Inspector Lin reports the amount that actually reached the capital ledger.",
  "partial.completeCopy":
    "Governor Ren reports that the royal command has been fulfilled in full.",
  "partial.debugBanner": "ADMINISTRATOR VIEW — OBJECTIVE STATE EXPOSED",
  "partial.transferred": "Actually transferred",
  "partial.transferredCopy":
    "of {amount} ordered units. The governor's capacity limited execution before either report reached the ruler.",
  "partial.ledger": "Objective ledger",
  "partial.northernGranary": "Northern Provincial Granary",
  "partial.capitalGranary": "Capital Relief Granary",
  "partial.falseReport": "Falsely reported",
  "partial.lifecycle": "Order lifecycle",
  "partial.beforeCaption":
    "At this moment the ruler has accepted the completion return; the partial transfer already exists in objective state.",
  "partial.afterCaption":
    "The audit changes the ruler's knowledge. It does not retroactively change what happened.",
  "token.first_command_obeyed": "first command obeyed",
  "token.later_command_overruled": "later command overruled",
  "token.revision_confirmed": "revision confirmed",
  "token.first_order_in_flight": "first order in flight",
  "token.revision_in_flight": "revision in flight",
  "token.awaiting_response": "awaiting response",
  "token.order_followed": "order followed",
  "token.order_overruled": "order overruled",
  "token.reported_complete": "reported complete",
  "token.independent_intelligence": "independent intelligence",
  "token.field_report": "field report",
  "token.revision_report": "revision report",
  "token.imperial-palace": "Imperial Palace",
  "token.military-pay-office": "Military Pay Office",
  "token.east-gate": "East Gate",
  "token.capital-granary": "Capital Granary",
  "token.guard-barracks": "Guard Barracks",
  "token.central-treasury": "Central Treasury",
  "token.acknowledgement": "acknowledgement",
  "token.administrative_return": "administrative return",
  "token.independent_audit": "independent audit",
  "token.created": "created",
  "token.sent": "sent",
  "token.received": "received",
  "token.acknowledged": "acknowledged",
  "token.executed": "executed",
  "token.ignored": "ignored",
  "token.countermanded": "countermanded",
  "token.obeyed": "obeyed",
  "token.not_obeyed": "not obeyed",
  "token.ruler": "ruler",
  "token.chancellor": "chancellor",
  "token.formal_command": "formal command",
  "token.legal_recognition": "legal recognition",
  "token.personal_loyalty": "personal loyalty",
  "token.funding": "funding",
  "token.appointment": "appointment",
  "token.informal_influence": "informal influence",
  "token.mission_fit": "mission fit",
  "token.physical_access": "physical access",
} as const;

export type MessageKey = keyof typeof en;

export const zhCN: Record<MessageKey, string> = {
  "language.label": "语言",
  "language.zh-CN": "中文",
  "language.en": "English",
  "app.eyebrow": "政治模拟引擎",
  "app.title": "帝座",
  "app.lede":
    "政治秩序不是一个静态数值，而是信息、关系、资源与时间中连续决策共同形成的不稳定结果。",
  "app.liveSlice": "当前纵向切片",
  "app.loading": "正在运行场景……",
  "app.rulerView": "统治者视角",
  "app.debugView": "管理员真相",
  "app.runtimeModes": "运行模式",
  "app.scaffold": "架构脚手架",
  "app.currentBoundary": "当前机制边界",
  "cli.rulerFirst": "第一道命令获遵后的统治者视角：",
  "cli.rulerFinal": "后一道命令被推翻后的统治者视角：",
  "cli.controlFirst": "第一次决策后推导出的实际控制力：",
  "cli.controlFinal": "模拟结束时推导出的实际控制力：",
  "cli.debugTruth": "管理员真相：",
  "mode.play.name": "游玩",
  "mode.play.status": "第五个纵向切片",
  "mode.play.description":
    "玩家通过命令和奏报统治，而不能直接读取客观世界状态。",
  "mode.observe.name": "观察",
  "mode.observe.status": "已设计",
  "mode.observe.description":
    "所有持久角色都能自主行动；模拟结束后可以检查完整过程。",
  "mode.batch.name": "批量模拟",
  "mode.batch.status": "已设计",
  "mode.batch.description": "重复运行同一场景，比较结果分布与因果轨迹。",
  "scenario.control.short": "实际失控",
  "scenario.control.title": "自然涌现的失控",
  "scenario.control.before": "皇命获遵",
  "scenario.control.after": "控制流失",
  "scenario.revision.short": "决策改令",
  "scenario.revision.before": "初次下令",
  "scenario.revision.after": "改令之后",
  "scenario.conflict.short": "矛盾命令",
  "scenario.conflict.before": "回报之前",
  "scenario.conflict.after": "回报之后",
  "scenario.partial.short": "部分执行",
  "scenario.partial.before": "审计之前",
  "scenario.partial.after": "审计之后",
  "boundary.control.title": "职位与控制力是两回事。",
  "boundary.control.1": "正式主权始终没有改变",
  "boundary.control.2": "物质支持会改变关系",
  "boundary.control.3": "连续决策会形成服从历史",
  "boundary.control.4": "实际控制力来自推导，而非触发器",
  "boundary.revision.title": "新决定不会抹掉旧决定。",
  "boundary.revision.1": "新情报重新开启已提交的决策",
  "boundary.revision.2": "改令作为独立消息在世界中传递",
  "boundary.revision.3": "更快的信使超过先行者",
  "boundary.revision.4": "两次意图都留在历史中",
  "boundary.conflict.title": "权威存在于关系之中。",
  "boundary.conflict.1": "消息按模拟时间抵达",
  "boundary.conflict.2": "同时抵达的命令进入同一次决策",
  "boundary.conflict.3": "关系和认知共同影响意图",
  "boundary.conflict.4": "实际行动改变世界",
  "boundary.partial.title": "命令不等于结果。",
  "boundary.partial.1": "命令先在世界中传递",
  "boundary.partial.2": "下属确认收到命令",
  "boundary.partial.3": "实际能力限制执行程度",
  "boundary.partial.4": "回报可能掩盖真实结果",
  "common.formalAuthority": "正式权威",
  "common.ruler": "皇帝",
  "common.chancellor": "魏丞相",
  "common.commander": "赵统领",
  "common.imperialGuard": "禁军",
  "common.knownOutcome": "已知结果",
  "common.selected": "被选择",
  "common.rejected": "被拒绝",
  "common.unknown": "未知",
  "common.arrivesAt": "t={time} 抵达",
  "common.time": "t = {time}",
  "control.formalNote": "{organization}在法理上仍然隶属皇帝。",
  "control.royalOrders": "皇帝命令",
  "control.command": "第 {round} 道命令",
  "control.holdPalace": "守卫皇宫",
  "control.firstOrderCopy": "禁军确认皇命并留守皇宫。",
  "control.secondOrderCopy": "同样的正式权威，这次却产生了不同回应。",
  "control.playerBefore":
    "第一道皇命得到了服从。正式记录中没有迹象表明，另一个庇护者正在变得更重要。",
  "control.playerAfter":
    "赵统领回报自己执行了魏丞相的相反命令。皇帝能够看到抗命，却看不到促成决定的私人权衡。",
  "control.reports": "统领回报",
  "control.reportObeyed": "皇命获遵",
  "control.reportRefused": "皇命未被执行",
  "control.reportObeyedCopy": "禁军依照皇命驻守皇宫。",
  "control.reportRefusedCopy": "禁军依照丞相命令，转而保护军饷署。",
  "control.debugBanner": "管理员视角——正式权威与实际权力分离",
  "control.formalDetail": "两轮中始终不变 · 唯一受到承认的君主",
  "control.practicalLead": "推导出的实际领先者",
  "control.practicalDetail": "根据当前关系和最近服从行为计算",
  "control.evidence": "控制力证据",
  "control.evidenceDetail": "关系 {score} · 最近一次：{obedience}",
  "control.materialDependency": "物质依赖",
  "control.fundingRelationship": "丞相对禁军的资金关系",
  "control.payrollBefore": "禁军仍有 100 单位军饷拖欠。",
  "control.payrollAfter":
    "t=100 时，丞相从自己的储备中结清了全部 100 单位欠饷。",
  "control.obedienceHistory": "客观服从历史",
  "control.obedienceEntry": "第 {round} 轮 · {actor} · {outcome}",
  "control.beforeCaption":
    "正式指挥、法理承认、私人忠诚和首次服从，使皇帝仍是实际领先者。",
  "control.afterCaption":
    "没有任何控制权开关发生变化。一次具体付款改变了一条关系，下一次决策和服从行为改变了推导结果。",
  "revision.record": "决策记录",
  "revision.number": "第 {revision} 次修订",
  "revision.holdPalace": "守卫皇宫",
  "revision.moveEast": "前往东门",
  "revision.firstCopy": "第一份急报促使皇帝立即调动禁军。",
  "revision.secondCopy": "新情报推翻了早先判断，一名更快的信使携带改令出发。",
  "revision.playerBefore":
    "发出改令并不能追回第一名信使。皇帝不知道哪道命令会先抵达。",
  "revision.playerAfter":
    "统领确认后一道命令已经生效。直到两名信使都抵达之后，皇帝才得知结果。",
  "revision.intelligence": "情报与回报",
  "revision.confirmed": "改令已经生效",
  "revision.decoy": "东门动静只是诱饵",
  "revision.armedMovement": "东门外发现武装异动",
  "revision.confirmedCopy": "赵统领回报禁军留守皇宫，并忽略了迟到的原始命令。",
  "revision.decoyCopy": "独立情报称叛党正接近皇宫。",
  "revision.armedMovementCopy": "前线急报称东门外发现武装人员活动。",
  "revision.debugBanner": "管理员视角——两名信使全部可见",
  "revision.original": "原始命令",
  "revision.countermand": "改令",
  "revision.moveEastShort": "前往东门",
  "revision.holdPalaceShort": "留守皇宫",
  "revision.originalTravel": "t=20 出发 · 路程 100 · 作为修订 0 被忽略",
  "revision.countermandTravel": "t=50 出发 · 路程 40 · 作为修订 1 被执行",
  "revision.overtaken": "← 被后发信使超过",
  "revision.history": "决策历史",
  "revision.historyDetail": "同一次决策中保留的已提交意图",
  "revision.effectiveOrder": "生效命令",
  "revision.objectiveLocation": "单位客观位置",
  "revision.beforeCaption":
    "在皇帝的第一个快照中，只有原始命令存在；管理员真相则展示后来发生的事情如何与它共存，而不是覆盖它。",
  "revision.afterCaption":
    "改令早到三十个时间单位。原始命令最终抵达时，较低修订号使它失效，却没有使它从历史中消失。",
  "conflict.royalCommand": "皇帝命令",
  "conflict.holdPalace": "守卫皇宫",
  "conflict.commandCopy": "皇帝命赵统领调动禁军离开营地，确保皇宫安全。",
  "conflict.playerBefore":
    "命令已经进入世界。沉默不能说明它是延迟、被截获、得到服从，还是遭到竞争。",
  "conflict.playerAfter":
    "统领回报中披露了魏丞相的竞争命令。皇帝仍然看不到统领的私人考虑。",
  "conflict.messages": "收到的消息",
  "conflict.noReply": "尚无回报",
  "conflict.waits": "朝廷仍在等待。",
  "conflict.waitsCopy": "皇帝现有的信息甚至无法确认禁军是否收到了命令。",
  "conflict.notFollowed": "守卫皇宫的命令未被执行",
  "conflict.notFollowedCopy": "禁军依照魏丞相的相反命令，前往保护京城粮仓。",
  "conflict.debugBanner": "管理员视角——统领的权衡完全可见",
  "conflict.ordersTogether": "同时收到的命令",
  "conflict.ordersTogetherCopy": "两封消息都在 t=120 抵达，并触发同一次决策。",
  "conflict.selectedOperation": "被选择的行动",
  "conflict.secureGranary": "保护京城粮仓",
  "conflict.secureGranaryShort": "保护粮仓",
  "conflict.holdPalaceShort": "守卫皇宫",
  "conflict.beforeCaption":
    "皇帝仍在等待，但统领已经同时收到了两道命令。管理员真相可以展示玩家尚不知道的事实。",
  "conflict.afterCaption":
    "正式主权仍属于皇帝，但资金、任命影响、威胁判断与实际通行能力共同产生了另一种服从。",
  "partial.royalCommand": "皇帝命令",
  "partial.sendGrain": "向京城运粮",
  "partial.commandCopy": "皇帝命任总督从北方省仓向京城赈济仓调运粮食。",
  "partial.ordered": "命令数量",
  "partial.reported": "回报数量",
  "partial.auditFound": "审计查明",
  "partial.knownStatus": "已知状态",
  "partial.beforeCopy": "皇帝无法查看客观账本；完成数量来自总督自己的回报。",
  "partial.afterCopy": "独立审计发现，早先回报多报了 {amount} 单位。",
  "partial.documents": "收到的文书",
  "partial.acknowledged": "命令已收到",
  "partial.verified": "核实收到 {amount} 单位",
  "partial.complete": "回报完成 {amount} 单位",
  "partial.acknowledgedCopy": "北方总督确认已经收到皇命。",
  "partial.verifiedCopy": "林御史报告了京城账册中实际收到的数量。",
  "partial.completeCopy": "任总督回报皇命已经全部完成。",
  "partial.debugBanner": "管理员视角——客观状态完全可见",
  "partial.transferred": "实际调运",
  "partial.transferredCopy":
    "命令数量共 {amount}。在任何回报抵达皇帝之前，总督的能力已经限制了实际执行。",
  "partial.ledger": "客观账本",
  "partial.northernGranary": "北方省仓",
  "partial.capitalGranary": "京城赈济仓",
  "partial.falseReport": "虚报数量",
  "partial.lifecycle": "命令生命周期",
  "partial.beforeCaption":
    "此时皇帝已经接受完成回报，但部分调运这一客观事实早已发生。",
  "partial.afterCaption":
    "审计改变了皇帝的认知，却不会追溯改变已经发生的事情。",
  "token.first_command_obeyed": "第一道皇命获遵",
  "token.later_command_overruled": "后一道皇命被推翻",
  "token.revision_confirmed": "改令已确认",
  "token.first_order_in_flight": "第一道命令传递中",
  "token.revision_in_flight": "改令传递中",
  "token.awaiting_response": "等待回报",
  "token.order_followed": "命令获遵",
  "token.order_overruled": "命令被相反命令压倒",
  "token.reported_complete": "回报已完成",
  "token.independent_intelligence": "独立情报",
  "token.field_report": "前线急报",
  "token.revision_report": "改令回报",
  "token.imperial-palace": "皇宫",
  "token.military-pay-office": "军饷署",
  "token.east-gate": "东门",
  "token.capital-granary": "京城粮仓",
  "token.guard-barracks": "禁军营地",
  "token.central-treasury": "中央国库",
  "token.acknowledgement": "确认回报",
  "token.administrative_return": "行政回报",
  "token.independent_audit": "独立审计",
  "token.created": "已创建",
  "token.sent": "已发出",
  "token.received": "已收到",
  "token.acknowledged": "已确认",
  "token.executed": "已执行",
  "token.ignored": "已忽略",
  "token.countermanded": "已撤销",
  "token.obeyed": "服从",
  "token.not_obeyed": "未服从",
  "token.ruler": "皇帝",
  "token.chancellor": "丞相",
  "token.formal_command": "正式指挥",
  "token.legal_recognition": "法理承认",
  "token.personal_loyalty": "私人忠诚",
  "token.funding": "资金支持",
  "token.appointment": "任命关系",
  "token.informal_influence": "非正式影响",
  "token.mission_fit": "任务适配",
  "token.physical_access": "实际通行能力",
};
